name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ vars.SSH_KEY }}

          script: |
            cd ~/apps/music-webhook
            git pull
            cd ~/apps
            docker compose up -d --build webhook
